### ISSUE TITLE
The References field is null when adding a schema

### ISSUE THREAD

**Issue by geob3d** [xnuinside/simple-ddl-parser#1]
HI @xnuinside 

First of all, I just wanted to tell you how amazing this parser is. I was testing the parser and noticed that the references fields in the Json output returns a value of "none" when adding a schema name to the table. For example if added the following values after REFERENCES, the "none" value appears:

other_schema.other_table
"other_schema".other_table

However, if just add the table name **other_table**, the references field does produce an out. Below is an example of the code that will reproduce the issue. 

```
from simple_ddl_parser import DDLParser


parse_results = DDLParser("""

 create table prod.super_table
(
    data_sync_id bigint not null default 0,
    id_ref_from_another_table int REFERENCES other_schema.other_table (id) --- this will product a null output. 
    primary key (data_sync_id, sync_start)
);

);


""").run()

print(parse_results) 
```

**Comment by xnuinside** [comment]
@geob3d, thank you for the feedback! I will fix it today and release new version little bit later :) you correct, I did not add schema support to references, need to fix it

**Comment by xnuinside** [comment]
@geob3d, I added support - https://github.com/xnuinside/simple-ddl-parser/pull/2, I plan to do several more things today and will release 0.4.0 with updates

**Comment by xnuinside** [comment]
@geob3d fix was released in 0.4.0 version, pls check

**Comment by geob3d** [comment]
Hi @xnuinside 

I just tested the changes on 0.4.0.  The schema support for references works as expected. I love the addition of the alter table statement to the parser. 

Thank you for the hard work as the project.  This parser is one of the best I've seen so far.

**Comment by xnuinside** [comment]
@geob3d  thank you :)
