### ISSUE TITLE
Adding CLUSTERED BY to HQL parser

### ISSUE THREAD

**Issue by swiatek25** [xnuinside/simple-ddl-parser#103]
Would that be possible to add CLUSTERED BY to the parser for HQL dialect?

Do you have any contribution guide so I could follow some instructions and do it by myself?

**Additional context**
* https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DDL+BucketedTables

**Comment by xnuinside** [comment]
@swiatek25 you can add it by yourself - needed only to add test in test cases with query and make required changes in code, but it's requireded some wish to work with ply - https://github.com/dabeaz/ply . when just open PR - I will review.

anyway, I can add support for this, I''m not sure that I will be able to do it today, but maybe tomorrow

**Comment by swiatek25** [comment]
Hi, thanks for the response. That would take some time for me (getting familiar with ply). If I could count on your contribution I would really appreciate. Thanks in advance.

**Comment by xnuinside** [comment]
@swiatek25  I released version 0.24.0 with support - https://pypi.org/project/simple-ddl-parser/. Tests added: https://github.com/xnuinside/simple-ddl-parser/blob/main/tests/test_hql_output_mode.py#L2006. If you will find any new issues or needed something to add - feel free to open new issue or PR. And thanks one more time for contribution :)
