### ISSUE TITLE
Table name which is also a "reserved word" fails to parse

### ISSUE THREAD

**Issue by nurih** [xnuinside/simple-ddl-parser#108]
Consider: 
```sql
create table index (col1:int);

create table foo.[index] (col1:int);

create table foo.index (col1:int);
```
The first 2 lines understand a table named  "index" is intended.
The third line classifies the word "index" as the token 'INDEX' [probably here](https://github.com/xnuinside/simple-ddl-parser/blob/04bb61a7c20a7542340a8834fafe182522783177/simple_ddl_parser/ddl_parser.py#L67).

Though not a good or recommended practice, table names are allowed to be arbitrary strings, even reserved words. 

If strict adherence to quoted/delimited usage of key-word-as-identifier DDL is desired, then the first line (bare "index" ) should have failed.
If relaxed adherence is intended, then all 3 should have succeeded.

**Comment by xnuinside** [comment]
@nurih I will fix it in next release, it should not recognise it as INDEX token in this statement.

**Comment by xnuinside** [comment]
@nurih can you clarify for me about 'col1:int' syntax, what DB support it? did not saw before that column name & type separated by ':'

**Comment by xnuinside** [comment]
@nurih I added the test for case """create table index (col1 int);
    create table foo.[index] (col1 int);
    create table foo.index (col1 int);
        """ https://github.com/xnuinside/simple-ddl-parser/blob/main/tests/test_simple_ddl_parser.py#L2389 and it works correctly in version 0.24.2 (already released), but syntax (col1:int) is not supported (question upper)

**Comment by nurih** [comment]
`(col1:int)` was a mistake. Should have been `(col1 int)`.

**Comment by nurih** [comment]
Very happy for this quick fix! Thank you!
