### ISSUE TITLE
Support Spark SQL (or HQL `USING` clause)

### ISSUE THREAD

**Issue by jpugliesi** [xnuinside/simple-ddl-parser#117]
**Is your feature request related to a problem? Please describe.**
Spark SQL DDL is very similar to HQL, with a notable difference being that Spark SQL supports a `USING` clause in `CREATE TABLE` statements (see the [DDL docs here](https://spark.apache.org/docs/latest/sql-ref-syntax-ddl-create-table-datasource.html)). 

The `USING` clause is importantly used for table definition in many storage formats provide APIs for Spark - for example, [Apache Iceberg](https://iceberg.apache.org/) and [Delta Lake](https://delta.io/)

**Describe the solution you'd like**
Support Spark SQL DDL parsing, likely as a simple extension of HQL, with support for the `USING` clause 

**Describe alternatives you've considered**
Potentially just support a `USING` clause in the HQL dialect parser

**Comment by xnuinside** [comment]
@jpugliesi  hi, I saw issue, sorry for the long answer and thanks for reporting this. But I sure that I cannot work on it in the nearest week. I think you know that is going on with Putins army.. we tries to leave country with family, I hope 2 weeks later I can work on it. sorry for the delay

**Comment by xnuinside** [comment]
It was hard month... I just released v0.26.0 - https://pypi.org/project/simple-ddl-parser/  and it contains support for USING statement. Test sample: https://github.com/xnuinside/simple-ddl-parser/blob/main/tests/test_spark_sql.py#L6 if you will find any statements that does not work correctly - feel free to open the new issue @jpugliesi
