### ISSUE TITLE
Parse adding a primary key as an alter table statement

### ISSUE THREAD

**Issue by couling** [xnuinside/simple-ddl-parser#119]
I'm trying to parse a sizeable DDL script with the primary key detached in separate `alter table` statements
```
alter table MY_TABLE
   add constraint PK_MY_TABLE primary key (DATETIME, REGIONID)
      using index tablespace SOME_TABLE_SPACE;
```
I notice it picks up the additional indexes, but at the moment `simple-ddl-parser` does not pick up the primary key when it's added in this way.

**Comment by xnuinside** [comment]
hello, sorry for delay without answer ) I thought this month will never share to me any time to fix issues.. but I released 0.26.0 with fix, test: https://github.com/xnuinside/simple-ddl-parser/blob/main/tests/test_alter_statements.py#L1718. Sorry one more time for the delay, feel free to open PR if you will find any new issue
