### ISSUE TITLE
CREATE OR REPLACE TABLE not recognized by parser

### ISSUE THREAD

**Issue by devxor** [xnuinside/simple-ddl-parser#131]
**Describe the bug**
CREATE OR REPLACE TABLE is not recognized. The parser returns empty list.

**To Reproduce**
I'm using "parse_from_file()". The DDL is from Snowflake DB.
Example of not working DDL:
```
create or replace table someTable (
    someField varchar(4)
);
```

**Expected behaviour**
See correct output.

**Comment by xnuinside** [comment]
@devxor hi! thanks for reporting the issue, I merged fix https://github.com/xnuinside/simple-ddl-parser/pull/132 & already released it in version 0.26.3 - https://pypi.org/project/simple-ddl-parser/
