### ISSUE TITLE
Permission denied warning on global install of the package and the first run in user mode

### ISSUE THREAD

**Issue by ivbeg** [xnuinside/simple-ddl-parser#138]
**Describe the bug**
If you install package globally 

**To Reproduce**
1. Run new clean installation "pip install simple-ddl-parser' without an any trace of the package in 'site-packages'
2. Check the folder and find that 'parsetab.py' file doesn't exist.
3. Run any script that calles simple_ddl_parser.parse_from_file from non root/non administrative user.
4. See error warning 'permission denied'

**Expected behavior**
Python packages shouldn't write into their package dir after installation.
If this file is required it should be generated during installation.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.10

**Comment by xnuinside** [comment]
@ivbeg  and again - thanks for reporting the issue, parsetab created by Ply, I tried include it in package, but I'm not sure that it will help, because as I see it is generated each run. Can you try 0.26.5 version?

**Comment by ivbeg** [comment]
@xnuinside sure, just I will write quite a lot of issues soon. I am parsing quite a big dataset of SQL files. Probably the next version?

**Comment by xnuinside** [comment]
@ivbeg  okay :) 😭

**Comment by xnuinside** [comment]
I will close this issue, because I tried to fix it in 0.26.5, if it will be still actual - reopen pls
