### ISSUE TITLE
Consider removing logging to parselog.txt from parser.py

### ISSUE THREAD

**Issue by ivbeg** [xnuinside/simple-ddl-parser#139]
**Is your feature request related to a problem? Please describe.**
Parselog.txt file created in the current working dir, but working directory could be read-only and it will cause unexpected errors.

**Describe the solution you'd like**
It's an unexpected behavior for python libs to create temporary or log files.  

**Describe alternatives you've considered**
Remove completely default logging code from 'parser.py' code; for testing purposes, use it inside tests scripts only.

**Comment by xnuinside** [comment]
@ivbeg  hi, Ivan, thanks for opening the issue, good point, can you try version 0.26.5? I made log file optional with argument. By default it shouldn't be created.

**Comment by xnuinside** [comment]
will close it as fixed
