### ISSUE TITLE
Please, remove "print" calls from library code

### ISSUE THREAD

**Issue by ivbeg** [xnuinside/simple-ddl-parser#141]
**Describe the bug**
Using 'print' is a bad practice for code debuging. Please remove print from output/common.py and dialects/snowflake.py. Better use logging module.

**To Reproduce**
1. Use simple-ddl-parser from any command like script

**Expected behavior**
Replace 'print' with 'logging.info' or 'logging.debug'. Avoid using 'print' in library code

**Comment by xnuinside** [comment]
initially was using print, because library expected only work as a console utility or script, but yes, make sense change to logging

**Comment by xnuinside** [comment]
@ivbeg done in release 0.28.0 I will close this issue
