### ISSUE TITLE
TypeError: sequence item 2: expected str instance, list found

### ISSUE THREAD

**Issue by ivbeg** [xnuinside/simple-ddl-parser#150]
**Describe the bug**
TypeError  sequence item 2: expected str instance, list found generated instead of DDLParserError

**To Reproduce**

1. Take file https://github.com/shurashs/CDW_DWH/blob/024dee59c808f8d57ef9694b7344917b54009b10/Projects/Metrics/Common/PT005/META/META_CRITERIA_COMBO.sql?raw=True
2. Use code ddl = parse_from_file(filepath)
3. See error TypeError  sequence item 2: expected str instance, list found

**Expected behavior**
DDLParserError with a clear error explanation

**More examples**
- https://github.com/DevStreet/FinanceAnalytics/blob/9dd4afee3dd8b0cee99dde57cb8879bc08f34f92/projects/OG-MasterDB/src/main/resources/db/create/hsqldb/sec/V_51__create_sec.sql?raw=True
- https://github.com/nikulinn/Joomlasite/blob/ff7ec716015559dda0cf6a519e49f6a117dde967/%D0%97%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B8/jdk1.7.0/demo/db/programs/toursdb/ToursDB_schema.sql?raw=True
- https://github.com/gmeurant/benerator/blob/a2cc4ab5bee15d464b76bf5c1db706dd97d7636d/benerator/tags/release-0.7.6/src/demo/resources/demo/shop/derby/create_tables.derby.sql?raw=True

**Comment by xnuinside** [comment]
fix released in version 0.27.0 (https://pypi.org/project/simple-ddl-parser/), continue working on other issues
