### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '*'

### ISSUE THREAD

**Issue by ivbeg** [xnuinside/simple-ddl-parser#151]
**Describe the bug**
ValueError: invalid literal for int() with base 10: '*' generated instead of DDLParserError

**To Reproduce**

1. Take file https://github.com/taozhaoping/ERP/blob/71ec472e9b793071a7eb52944883382e83cc4629/setup/sql/activiti/createAct/activiti.oracle.create.engine.sql?raw=True
2. Use code ddl = parse_from_file(filepath)
3. See error ValueError: invalid literal for int() with base 10: '*'

**Expected behavior**
DDLParserError with a clear error explanation

**More examples**
- https://github.com/codehaus/activiti/blob/fa3811b06f205e791305c21a5a3544c8f4d30846/activiti/tags/activiti-5.8/modules/activiti-engine/src/main/resources/org/activiti/db/create/activiti.oracle.create.engine.sql?raw=True
- https://github.com/hungud/Telecommunication/blob/d6baf8d57d5e6924ad57ea88e7b6d496daaabb2d/SIM_TRADE/DataBase/SCRIPTS_FROM_DB/SIM_TRADE/TABLE/DB_LOADER_ACCOUNT_PHONES.SQL?raw=True
- https://github.com/aisaenko/pre-3.1-Openclinica/blob/82c6a18dc0ee1ea2da1ec5f8e3ccd9baa358b76d/OpenClinica/tags/OpenClinica-3.0-beta3/src/main/config/database/Oracle/3.0-beta3/upgrade/schema_patch_2.5_to_3.0.sql?raw=True

**Comment by xnuinside** [comment]
fix released in version 0.27.0 (https://pypi.org/project/simple-ddl-parser/), will continue work on another issues)
