### ISSUE TITLE
Issues parsing AUTOINCREMENT together with NOT NULL statement

### ISSUE THREAD

**Issue by devxor** [xnuinside/simple-ddl-parser#170]
**Describe the bug**
When there is `NOT NULL` statement before `AUTOINCREMENT` statement the parser is not returning results.

**To Reproduce**
```
CREATE OR REPLACE TABLE mytable (
    field_1 NUMBER(38, 0) NOT NULL AUTOINCREMENT
);
```

**Expected behavior**
Results parsed correctly.

**Question:
When I will remove `NOT NULL` in the above example, it will be parsed, however the type of the column will be displayed as `NUMBERAUTOINCREMENT`. Is it correct? Should not be only `NUMBER` and AUTOINCREMENT as a separate flag or so?

**Comment by xnuinside** [comment]
@devxor I just released version 0.29.0 with fix. Try it! Test added here https://github.com/xnuinside/simple-ddl-parser/blob/main/tests/test_simple_ddl_parser.py#L3121

thanks for opening the issue & feel free to open new one if needed anything more
