### ISSUE TITLE
Support REFERENCES `ON` construction

### ISSUE THREAD

**Issue by walkman90** [xnuinside/simple-ddl-parser#18]
Adding `ON DELETE CASCADE` or similar `ON` construction after `REFERENCES ...` leads to an empty parse result.
It would be nice to support `ON` also.

Thanks! Cool parser BTW :)

**Comment by xnuinside** [comment]
@walkman90 , hello & thank you! Good addition. I will be back from vacation on 31 March and will add support in parser.

**Comment by xnuinside** [comment]
@walkman90  hello! I added feature in release 0.9.0 (already released). Example of output: https://github.com/xnuinside/simple-ddl-parser/blob/main/tests/test_references.py#L37. Please comment if you will find any issues or need to add smth else.

**Comment by xnuinside** [comment]
I will close issue as done, if you will have anything more - feel free to open a new one.
