### ISSUE TITLE
Oracle global temporary table no supported

### ISSUE THREAD

**Issue by ancc** [xnuinside/simple-ddl-parser#182]
Following create table statement is not recognized by the parser, which is valid statement for Oracle database.

```
from simple_ddl_parser import DDLParser
DDLParser("create global temporary table test (id number);").run()
```
result is empty list.

python version 3.9.5
simple-ddl-parser==0.29.1

**Comment by xnuinside** [comment]
create global temporary table - not supported yet, I will add it, thanks for opening the issue!

**Comment by xnuinside** [comment]
Added in version 1.4.0 - https://github.com/xnuinside/simple-ddl-parser/pull/252. I will close this issue. If needed anything else, feel free to open the new one!
