### ISSUE TITLE
IDENTITY clause in column definition not handled

### ISSUE THREAD

**Issue by ctimmer** [xnuinside/simple-ddl-parser#184]
**Describe the bug**
SQLServer - INDENTITY clause in column definition causes a problem with the entry size

**To Reproduce**
In the ddl:
[cifno] [numeric](10, 0) IDENTITY(1,1) NOT NULL,
puts (1,1) in the size field

**Expected behavior**
Either ignore the IDENTITY clause or create a separate object entry for the identity value

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser chrome
 - Version 01/10/2023

**Comment by xnuinside** [comment]
fix prepared in https://github.com/xnuinside/simple-ddl-parser/pull/195, I will comment one more time after version 0.30.0 will be released

**Comment by xnuinside** [comment]
@ctimmer just released version 0.30.0. Try it, test was added - https://github.com/xnuinside/simple-ddl-parser/blob/main/tests/dialects/test_mysql.py#L315. If will be needed something new - feel free to open the issue.
