### ISSUE TITLE
Parsing fails for GENERATED ALWAYS AS expressions that use a cast

### ISSUE THREAD

**Issue by bholzer** [xnuinside/simple-ddl-parser#198]
Minimal example:

```
CREATE TABLE test (
  timestamp TIMESTAMP,
  date DATE GENERATED ALWAYS AS (CAST(timestamp AS DATE))
)
```

Trying to dig into the code to see if I can issue a PR for this myself.

**Comment by xnuinside** [comment]
Hi! I'm not sure why I ignore this issues, sorry for that! @bholzer thank you for opening it and support for CAST added in version 1.2.0, test added - https://github.com/xnuinside/simple-ddl-parser/blob/main/tests/dialects/test_psql.py#L45. If will be any other issues, feel free to open new one and thank you again!
