### ISSUE TITLE
VISIBLE keyword causes parser error

### ISSUE THREAD

**Issue by timothy-r** [xnuinside/simple-ddl-parser#243]
**Describe the bug**
Reading an SQL DDL that uses the VISIBLE keyword causes an error and the entire table definition is not read

**To Reproduce**
1. Write an SQL create table statement with an index that uses the VISIBLE keyword
2. Read the SQL with the ddl parser
3. See the error generated

**Expected behavior**
DDL parser should read SQL DDL statements with the VISIBLE keyword

**Comment by xnuinside** [comment]
released in version 1.1.0,  added in PR: https://github.com/xnuinside/simple-ddl-parser/pull/246/files
if will be needed anything else - feel fre to re-open this issue or create new one
