### ISSUE TITLE
Using Postgres type `timestamp with time zone` results to table not appearing in the list

### ISSUE THREAD

**Issue by umaxfun** [xnuinside/simple-ddl-parser#250]
The code 
```python
from simple_ddl_parser import ddl_parser

sql = "CREATE TABLE public.test (date_updated timestamp with time zone);"
result = ddl_parser.DDLParser(sql).run()
print(result)
```

results in `[]`

This type is used by Directus CMS, so I can't use another type =(

**Comment by xnuinside** [comment]
@umaxfun Hi! Thanks for opening the issue. I released the fix in version 1.3.0 - https://pypi.org/project/simple-ddl-parser/. Test was added: https://github.com/xnuinside/simple-ddl-parser/blob/main/tests/dialects/test_psql.py#L118 
If will be needed anything else - feel free to open new issue!
