### ISSUE TITLE
Snowflake dialect missing Insert and Delete values

### ISSUE THREAD

**Issue by HalfonA** [xnuinside/simple-ddl-parser#270]
**Describe the bug**
Hi, I parse some logs of queries and I stumbled upon this bug:
When using the parser with `snowflake` dialect, `select` and `create` works fine, but `delete` and `insert` returns empty lists- meaning no tables detected.

**To Reproduce**
```ipython
In [11]: ddl = """INSERT INTO TDM . CLEANSED . I_TRACKING (ID, BATCH_SIZE, SOURCE, SNOWFLAKE_BATCH_COMMIT_TS, BATCH_MIN_SOURCE_TS, BATCH_MAX_SOURCE_TS, MIN_OFFSET, MAX_OFFSET, K_PARTITION, IR, DUP_K_DROPS, TABLE_NAME ) VALUES ( ? )"""

In [12]: DDLParser(ddl).run(output_mode="snowflake")
Out[12]: []
```

```ipython
In [15]: ddl =  """DELETE FROM SL_CHANGE WHERE A_CHANGE_ID = ?"""

In [16]: DDLParser(ddl).run(output_mode="snowflake")
Out[16]: []
```

**Expected behavior**
I expect for the `insert` case, to have `TDM.CLEANSED.I_TRACKING` as a table, containing these columns:
`ID, BATCH_SIZE, SOURCE, SNOWFLAKE_BATCH_COMMIT_TS, BATCH_MIN_SOURCE_TS, BATCH_MAX_SOURCE_TS, MIN_OFFSET, MAX_OFFSET, K_PARTITION, IR, DUP_K_DROPS, TABLE_NAME`
as a dict

for the `delete` case the same thing - 
`SL_CHANGE` as the `table_name` and `A_CHANGE_ID` as the column

**Desktop:**
 - OS: Mac
 - Version 1.5.1

**Additional context**
I tried changing the `?` for another value but it didn't make any change
for the insert ddl specifically, I also tried removing the spaces in the table name but it didn't make any change either

**Comment by xnuinside** [comment]
@HalfonA, hi, thanks for opening the issue, problem, that insert & delete is not supported. Also, DELETE & INSERT is not a part of DDL - it is a DML, so DML is not supported at all.

**Comment by dmaresma** [comment]
Hi Halfon A. can I suggest you to look at the role of this python module : https://github.com/tobymao/sqlglot it seems the good one for you.

**Comment by xnuinside** [comment]
@HalfonA no ) it wasn’t planned, only ddl. I agree with @dmaresma, better to take a look on sqlglot

**Comment by HalfonA** [comment]
Thank you!
