### ISSUE TITLE
Feature: add support of Trino (AWS Athena) dialect

### ISSUE THREAD

**Issue by roykoand** [xnuinside/simple-ddl-parser#272]

**Comment by xnuinside** [comment]
@roykoand , hi! thanks for opening an issue, I'm on conference this week. I can take a look on dialect next week. As I understand in first priority samples of dialect, that are provided here - https://github.com/datacontract/datacontract-cli/issues/332 ?

**Comment by roykoand** [comment]
@xnuinside Yes, this is correct. Very much appreciated! Thanks in advance!

**Comment by xnuinside** [comment]
@roykoand Can I ask, why you choose for your project simple-ddl-parser, but not sqlglot for example? Historically was the reasons, why I created this library, but now as I see, sqlglot already supports different dialects very well & better then my parser. Is it because of output format? I’m trying to understand why peoples still use & staring use my parser. I’m thinking about to add sqlglot as extension dependency in my parser like to use it as parser engine, but sabe same output structure

**Comment by roykoand** [comment]
@xnuinside this is a great question! I am not an original developer who introduced this dependency, I am not more than a person who just did a feature request.
I think you're correct in your assumption, nice and easy to work with output format is a key for why folks prefer to use `simple-ddl-parser`. @jochenchrist maybe you can add more details on your motivation of using `simple-ddl-parser` in `datacontract-cli`, thanks in advance!

**Comment by jochenchrist** [comment]
Author of datacontract-cli here.
Well, `simple-ddl-parser` did exactly the job to parse CREATE TABLE statements to import them to a data contract.

We discussed using sqlglot for exporting to different formats, but we would have the need to override the data type if a server-specific data type is defined in a data contract. Seems a little complicated.

https://github.com/datacontract/datacontract-cli/issues/160

**Comment by xnuinside** [comment]
@roykoand @jochenchrist added output for Athena in 1.6.0 and added your case to test cases - https://github.com/xnuinside/simple-ddl-parser/blob/main/tests/dialects/test_athena.py#L6. Please, use: https://pypi.org/project/simple-ddl-parser/1.6.0/. 

@jochenchrist thanks for answer :)  

I will close this issue - if needed anything else, feel free to open new one.

**Comment by roykoand** [comment]
@xnuinside Thank you so much for adding Athena (Trino) dialect! Excited to try it out!
