### ISSUE TITLE
CREATE SCHEMA IF NOT EXISTS STATEMENT with COMMENT

### ISSUE THREAD

**Issue by dmaresma** [xnuinside/simple-ddl-parser#281]
**Describe the bug**
the following SQL statement fail : 
`CREATE SCHEMA IF NOT EXISTS TESTBLABLA COMMENT='my blabla comment';`

`from simple_ddl_parser import DDLParser
local_ddl = """CREATE SCHEMA IF NOT EXISTS TESTBLABLA COMMENT='my blabla comment';"""
schema_if_not_exists = DDLParser(local_ddl).run(output_mode="snowflake")
expected = [{'if_not_exists': True, 'schema_name': 'TESTBLABLA', 'comment': "'my blabla comment'"}]
#schema_if_not_exists
assert(schema_if_not_exists == expected)`

The schema / schema_name is not detected.

**Comment by dmaresma** [comment]
if I remove lines `        | create_schema id id id
        | create_schema id id STRING` from `p_create_schema` in `sql.py` everything is back to normal, all test in success (supposed to mean no regressions)

**Comment by xnuinside** [comment]
@dmaresma we can remove it if all tests are green, maybe some artefact from the past. I always adding tests for statements, so if tests are green - feel free to delete it, or I can do it on weekends
