### ISSUE TITLE
MSSQL/TSQL Support

### ISSUE THREAD

**Issue by geob3d** [xnuinside/simple-ddl-parser#29]
Hi @xnuinside 

I hope your are doing well. I saw that you made some major enhancements since to this project (FYI this is still amazing). I  wanted to provide this comprehensive query for when you plan to add MS/T SQL support to the parser. You will notice that Postgres and MS SQL have  similar syntaxes . The DDL below includes almost every TSQL data type. I also included the max sizes for each of the data types. Please feel free to let me know if you have any issues with the query. 

```
CREATE TABLE Persons (
    PersonID int PRIMARY KEY,
    LastName varchar(255),
    FirstName varchar(255),
    Address varchar(255),
    City varchar(255)
);


CREATE TABLE sqlserverlist (

id INT IDENTITY (1,1) PRIMARY KEY, -- NOTE THE IDENTITY (1,1) IS SIMILAR TO serial in postgres - Format for IDENTITY [ (seed , increment) ]
company_id BIGINT ,
primary_id INT FOREIGN KEY REFERENCES Persons(PersonID), -- ADD THIS COLUMN FOR THE FOREIGN KEY
age TINYINT NULL UNIQUE,
days_active SMALLINT NOT NULL,
user_origin_of_birth char(255),
user_account VARCHAR(8000) NOT NULL,
user_first_name VARCHAR(max) NOT NULL,
user_last_name 	VARBINARY(8000) NOT NULL,
user_street NCHAR(400) NULL,
user_city NVARCHAR(4000),
about_user NTEXT NULL,
user_description TEXT,
starting_funds FLOAT(53) NULL,
extra_funds REAL,
current_funds DECIMAL (38,20),
ending_funds SMALLMONEY NOT NULL,
birth_date DATE NOT NULL,
time_of_birth TIME(7),
enrollment_date SMALLDATETIME,
delete_date DATETIME NULL,
create_date DATETIME2(7) NOT NULL,
user_time_zone DATETIMEOFFSET(7),
oder_date date DEFAULT GETDATE(), -- added to demonstrate sql sever Defaults
country varchar(255) DEFAULT 'Sandnes', -- added to demonstrate sql sever Defaults
active bit NULL,
home_size GEOMETRY, -- Sql Server Defaults to Null
user_photo IMAGE, -- Sql Server Defaults to Null
--UNIQUE (id),
CONSTRAINT UC_sqlserverlist_last_name UNIQUE (company_id,user_last_name),
CONSTRAINT CHK_Person_Age_under CHECK (days_active<=18 AND user_city='New York'),
FOREIGN KEY (id) REFERENCES Persons(PersonID),
CONSTRAINT FK_Person_Age_under  FOREIGN KEY (id)REFERENCES Persons(PersonID)
)

-- UNIQUE CONSTRAINTS
ALTER TABLE sqlserverlist ADD UNIQUE (birth_date);
ALTER TABLE sqlserverlist ADD CONSTRAINT UC_Person_ening_funds UNIQUE (current_funds,create_date);
--CHECK CONSTRAINTS
ALTER TABLE sqlserverlist ADD CHECK (starting_funds>=0);
ALTER TABLE sqlserverlist ADD CONSTRAINT CHK_Person_Age CHECK (age >=18 AND user_city='Sandnes');
-- FOREIGN KEY Constraints
ALTER TABLE sqlserverlist ADD FOREIGN KEY (id) REFERENCES Persons(PersonID);
ALTER TABLE sqlserverlist ADD CONSTRAINT FK_PersonOrder4 FOREIGN KEY (id) REFERENCES Persons(PersonID);
-- INDEXES 
CREATE INDEX i1 ON sqlserverlist (extra_funds);
--CREATE CLUSTERED INDEX i2 ON sqlserverlist  (delete_date,create_date); --- This line is commented because TSQL doesnt allow two index on table added as an example
--CREATE UNIQUE INDEX i1 ON t1 (delete_date DESC, create_date ASC, ending_funds  DESC); --- This line is commented because TSQL doesnt allow two index on table added as an example

-- DEFAULTS
ALTER TABLE sqlserverlist ADD CONSTRAINT df_user_street DEFAULT '1 WAY STREET' FOR user_street;
SELECT * FROM #sqlserverlist
```

**Comment by xnuinside** [comment]
Hi, thank you! It is very useful, I will check how parser work with them right now and will add to the tests. One thing that I see ‘by eyes’ it’s exactly Identity - need to add support to it, because in syntax right now expected column_name type (size) and here column_name type type (size). I’m not sure how correct parse types this way. In PostgreSQL type just defined like SERIAL or BIGSERIAL. So output just ‘type’: ‘SERIAL’ like any other type. Here when type will be ‘int IDENTITY’ is it ok or maybe any thoughts how do it better?

**Comment by geob3d** [comment]
HI @xnuinside 

You are correct, the best approach would be to use 'int IDENTITY’ as a type. T-SQL does not allow  'Identity'  to be present without declaring an integer data type on the column.  Below is a DDL example that demonstrates which data types can be used with "Identity".


```
create table temp(
id INT IDENTITY (1,1) not null,
user_num BIGINT IDENTITY (1,1),
user_digits SMALLINT IDENTITY (1,1),
user_code TINYINT IDENTITY (1,1)
)
```

**Comment by xnuinside** [comment]
@geob3d, hello! thanks for huge example - it is very useful, I released 0.12.0-a0 (PR with tests here): https://github.com/xnuinside/simple-ddl-parser/pull/31 you can test it, but I not done yet, need to add support for 
--CREATE UNIQUE INDEX i1 ON t1 (delete_date DESC, create_date ASC, ending_funds  DESC);  (usage 'DESC' near column)
and 
ALTER TABLE sqlserverlist ADD CONSTRAINT df_user_street DEFAULT '1 WAY STREET' FOR user_street;

but you can test that already done

**Comment by xnuinside** [comment]
@geob3d, hi! I just released version 0.12.0 https://pypi.org/project/simple-ddl-parser/ . Your whole example must works, please check. If you will find any issues - just comment about them. But after `CONSTRAINT FK_Person_Age_under  FOREIGN KEY (id)REFERENCES Persons(PersonID)
)` need to put ';' of course to separate statements.

**Comment by geob3d** [comment]
HI @xnuinside 

I can certainly take a look. Last week was  a little busy but I will do some tests this week and confirm that the parser is working for  MSSQL. I have already started working on the MSSQL syntax and I will open a new issue we complete this one.

**Comment by xnuinside** [comment]
@geob3d Did you have a time? btw https://xnuinside.medium.com/code-generation-how-to-generate-pydantic-sqlalchemy-ginoorm-models-from-sql-ddl-2c111b08b7a7 (at the end of article - thanks for you :))

**Comment by geob3d** [comment]
Hi @xnuinside 

Thank you for the shout out on your article! I am happy to know that I was happy enough to get the honor. You have been working very hard on this wonderful project and I cannot thank you enough for the work that you put in. I look forward to make as many contributions as I can.

Now for the some testing results. I decided to review the table output first. I noticed that the bellow line in the Sql Syntax adds an extra quote with conditions that have character spaces:
`
CONSTRAINT CHK_Person_Age_under CHECK (days_active<=18 AND user_city='New York'),`

The output in the dictionary becomes 

```
'constraints': {'checks': [{'constraint_name': 'CHK_Person_Age_under',
                                                 'statement': "days_active<=18 AND user_city='New "
                                                              "York'"}],
```

I am not sure if that intentional but it didn't seem to match your current format. 
I also noticed that I did not provide you the inline table format for indexes. I will send you that after I post about my statements on the "alter statements"

PS: 
That SQLAlchemy/GinoORM is a dream come true.  I would be more than happy to help you with other ORMs or web frameworks.

**Comment by geob3d** [comment]
Hi @xnuinside 

I reviewed the alter statement and everything looks great !

**Comment by xnuinside** [comment]
@geob3d , hi, thanks for the catch "days_active<=18 AND user_city='New "
                                                              "York'" looks like a bug - I will try to fix it

**Comment by xnuinside** [comment]
@geob3d, I checked the output, if print 
print(result['tables'][0]['constraints']['checks'][0]['statement'])
if will return normal str `days_active<=18 AND user_city='New York'`

Magic with new line and spaces add just by **pprint** that I used to display output, so it's not a bug )) but strange format from pprint. Can I close the issue?

**Comment by geob3d** [comment]
Hi @xnuinside 

Thank you for taking a look. You can close this issue. I will open another issue if i see another issue. Once again thank you for all the amazing work!

Regards 
George
