### ISSUE TITLE
Default value with expression

### ISSUE THREAD

**Issue by walkman90** [xnuinside/simple-ddl-parser#39]
**Describe the bug**

For such an example, where default value contains expression - the table is missing in result:
```sql
CREATE TABLE foo
(
    bar_timestamp  bigint DEFAULT (extract(epoch from now()) * 1000)
);
```
*Postgresql dialect

**Comment by xnuinside** [comment]
@walkman90, thank you for reporting an issue! I will take in work both issues on this weekend.

**Comment by xnuinside** [comment]
@walkman90, hello again!  fixes was done in 0.15.0 version https://pypi.org/project/simple-ddl-parser/, test case with your sample and output: https://github.com/xnuinside/simple-ddl-parser/blob/main/tests/test_simple_ddl_parser.py#L1125

**Comment by walkman90** [comment]
thank you for a quick fix, works like a charm!

**Comment by xnuinside** [comment]
@walkman90 can I close the issues?

**Comment by walkman90** [comment]
yes, sure
