### ISSUE TITLE
Primary key with default value

### ISSUE THREAD

**Issue by walkman90** [xnuinside/simple-ddl-parser#40]
**Describe the bug**

If the primary key defined with a DEFAULT value - the parser won't treat it as a primary key in the result

```sql
CREATE TABLE foo
(
    entity_id        UUID PRIMARY KEY DEFAULT getId()
);
```
* `getId()` is a function that generate UUID
* Postgresql dialect 

In result: `'primary_key': []`

**Comment by xnuinside** [comment]
@walkman90, hello! I released fixes in 0.15.0 version https://pypi.org/project/simple-ddl-parser/, test case with your sample and output: https://github.com/xnuinside/simple-ddl-parser/blob/main/tests/test_simple_ddl_parser.py#L1084
