### ISSUE TITLE
Enum handling

### ISSUE THREAD

**Issue by walkman90** [xnuinside/simple-ddl-parser#44]
Postgres dialect allows to define enumerations as a type, for example:

```sql
CREATE TYPE my_status AS enum (
    'NEW',
    'IN_PROGRESS',
    'FINISHED'
);

CREATE TABLE foo
(
    entity_id        UUID PRIMARY KEY DEFAULT getId(),
    status           my_status
);
```

Right now parser will fail in this case with:
`ValueError: dictionary update sequence element #0 has length 1; 2 is required`

It would be nice if the parser could just omit enum definitions. 
Or support enum parsing as well if you think it is make sense.

One more example of enum definition for testing:
```sql
DO
$$
    BEGIN
        IF NOT EXISTS(SELECT 1
                      FROM pg_type
                      WHERE typname = 'my_status')
        THEN
            CREATE TYPE my_status AS enum (
                'NEW',
                'IN_PROGRESS',
                'FINISHED'
                );
        END IF;
    END
$$;
```

**Comment by xnuinside** [comment]
@walkman90, hi, thanks for reporting an issue. for this example, 
```
DO
$$
    BEGIN
        IF NOT EXISTS(SELECT 1
                      FROM pg_type
                      WHERE typname = 'my_status')
        THEN
            CREATE TYPE my_status AS enum (
                'NEW',
                'IN_PROGRESS',
                'FINISHED'
                );
        END IF;
    END
$$;
```
a lot of thinks are not done, I did not planned to support DO BEGIN statements yet

To be honest, Enum was added https://github.com/xnuinside/simple-ddl-parser/blob/main/tests/test_simple_ddl_parser.py#L983 so looks like there is some bug, that I need to check.

**Comment by xnuinside** [comment]
@walkman90, I released version 0.16.1 with fix. Now this ddl 
```

CREATE TYPE my_status AS enum (
    'NEW',
    'IN_PROGRESS',
    'FINISHED'
);

CREATE TABLE foo
(
    entity_id        UUID PRIMARY KEY DEFAULT getId(),
    status           my_status
);

```
produces the output:

`{'tables': [{'columns': [{'name': 'entity_id', 'type': 'UUID', 'size': None, 'references': None, 'unique': False, 'nullable': False, 'default': 'getId()', 'check': None}, {'name': 'status', 'type': 'my_status', 'size': None, 'references': None, 'unique': False, 'nullable': True, 'default': None, 'check': None}], 'primary_key': ['entity_id'], 'alter': {}, 'checks': [], 'index': [], 'partitioned_by': [], 'tablespace': None, 'schema': None, 'table_name': 'foo'}], 'types': [{'schema': None, 'type_name': 'my_status', 'base_type': 'enum', 'properties': {'values': ["'NEW'", "'IN_PROGRESS'", "'FINISHED'"]}}], 'sequences': [], 'domains': [], 'schemas': []}`

**Comment by walkman90** [comment]
that more than enough for me, thanks a lot for a quick fix

**Comment by xnuinside** [comment]
@walkman90, if you will find any new issues - you know that to do :) thanks for the reports!
