### ISSUE TITLE
'key' as a column name

### ISSUE THREAD

**Issue by walkman90** [xnuinside/simple-ddl-parser#47]
The table will be skipped if it has a column named 'key'

```sql
CREATE TABLE foo
(
    entity_id        UUID PRIMARY KEY DEFAULT getId(),
    key              VARCHAR(256)
);
```

Output `[]`

**Comment by xnuinside** [comment]
@walkman90 and I know the reason )) I will need some time to think how to fix it

**Comment by xnuinside** [comment]
@walkman90 I released version 0.16.3 with the fix, please try it

**Comment by walkman90** [comment]
perfect, thank you!

**Comment by xnuinside** [comment]
@walkman90, I will close the issue, you know that to do if something will be wrong :)
