### ISSUE TITLE
Adding Support for Check Constratint

### ISSUE THREAD

**Issue by geob3d** [xnuinside/simple-ddl-parser#5]
Hi @xnuinside 

I was wondering if you plan on adding support for check constraints. Below are some examples for the check.

CREATE TABLE employees (
	id SERIAL PRIMARY KEY,
	first_name VARCHAR (50),
	last_name VARCHAR (50),
	birth_date DATE CHECK (birth_date > '1900-01-01'),
	joined_date DATE CHECK (joined_date > birth_date),
	salary numeric CHECK(salary > 0)
);
CREATE TABLE Persons (
    ID int NOT NULL,
    LastName varchar(255) NOT NULL,
    FirstName varchar(255),
    Age int,
    City varchar(255),
    CONSTRAINT CHK_Person CHECK (Age>=18 AND City='Sandnes')
);

ALTER TABLE Persons
ADD CHECK (Age>=18);

**Comment by xnuinside** [comment]
I will add it to TODO list

**Comment by xnuinside** [comment]
@geob3d, I added full support to CHECK statement based on your example )) https://github.com/xnuinside/simple-ddl-parser/pull/6 pls review. I will tomorrow add docs, if you will have any suggestions or comments - add in PR. Full your example, you can find in test test_alter_check_combine_all_variants in file test_alter_statements.py

**Comment by xnuinside** [comment]
done in https://github.com/xnuinside/simple-ddl-parser/pull/6
