### ISSUE TITLE
Typo in Partition By parsing

### ISSUE THREAD

**Issue by antoine-lefebvre** [xnuinside/simple-ddl-parser#57]
**Describe the bug**

Based on the documentation (and looking at the source code and tests), the keyword matched for partitioning is "PARTITIONED BY".
But the actual SQL syntax is "PARTITION BY".

This result in the parsing not working.

Could you please fix this issue?

`
CREATE TABLE table_name
(
    table_id INT64,
    a_column STRING,
    another_column BOOLEAN,
    a_partion_column DATE
)
PARTITION BY a_partion_column
`

**Comment by xnuinside** [comment]
@antoine-lefebvre hi! I released version 0.19.4 https://pypi.org/project/simple-ddl-parser/ and added several test https://github.com/xnuinside/simple-ddl-parser/blob/main/tests/test_after_columns_statements.py#L1049 https://github.com/xnuinside/simple-ddl-parser/blob/main/tests/test_after_columns_statements.py#L140, you can check result here - if will be any issues/bugs or features to add - please feel free to open new issue
