### ISSUE TITLE
Cannot use special character like # or | on COMMENT

### ISSUE THREAD

**Issue by kukigai** [xnuinside/simple-ddl-parser#60]
**Describe the bug**
Cannot use special character like # or | on COMMENT

**To Reproduce**
Try to parse

ddl = """
CREATE EXTERNAL TABLE `test` (
    job_id STRING NULL COMMENT 'test'
)
STORED AS PARQUET LOCATION 'hdfs://test'
"""
from simple_ddl_parser import DDLParser
parse_results = DDLParser(ddl).run(output_mode="hql")

**Expected behavior**
Should get json result but got empty.

**Comment by xnuinside** [comment]
@kukigai I added test case for special characters here https://github.com/xnuinside/simple-ddl-parser/blob/main/tests/test_hql_output_mode.py#L1639 & released version 0.19.5 with fix. Feel free to open new issue if needed. And thanks for the report!

**Comment by kukigai** [comment]
Thanks for the quick fix but found a new issue.  https://github.com/xnuinside/simple-ddl-parser/issues/63
