### ISSUE TITLE
DDL statement without "NULL" or "not NULL" is not supported

### ISSUE THREAD

**Issue by kukigai** [xnuinside/simple-ddl-parser#61]
**Describe the bug**
DDL statement without "NULL" or "not NULL" is not supported

**To Reproduce**
The following failed. (empty response)
ddl = """
CREATE EXTERNAL TABLE `test` (
    job_id STRING COMMENT 'test'
)
STORED AS PARQUET LOCATION 'hdfs://test'
"""
from simple_ddl_parser import DDLParser
parse_results = DDLParser(ddl).run(output_mode="hql")

But the following passed.
ddl = """
CREATE EXTERNAL TABLE `test` (
    job_id STRING NULL COMMENT 'test'
)
STORED AS PARQUET LOCATION 'hdfs://test'
"""
from simple_ddl_parser import DDLParser
parse_results = DDLParser(ddl).run(output_mode="hql")

**Expected behavior**
Above both cases should return the same result.

**Comment by xnuinside** [comment]
@kukigai, hello. In test there are a lot of samples without null statements https://github.com/xnuinside/simple-ddl-parser/blob/main/tests/test_simple_ddl_parser.py#L13. I think problem in something else. I will check at the evening both issues & will try fix as soon as possible

**Comment by xnuinside** [comment]
okay, I got reason ) problem in 'COMMENT' without nulls.. I will try to fix it

**Comment by xnuinside** [comment]
@kukigai I released version 0.19.5 https://pypi.org/project/simple-ddl-parser/ with fix & test case here - https://github.com/xnuinside/simple-ddl-parser/blob/main/tests/test_hql_output_mode.py#L1567. Thanks for the report! And feel free to open new issue, if you will find anything.
