### ISSUE TITLE
Question mark in COMMENT is not handled

### ISSUE THREAD

**Issue by kukigai** [xnuinside/simple-ddl-parser#64]
**Describe the bug**
Question mark in COMMENT is not handled

**To Reproduce**
ddl = """
CREATE EXTERNAL TABLE `test` (
    job_id STRING COMMENT 'test?'
)
STORED AS PARQUET LOCATION 'hdfs://test'
"""
from simple_ddl_parser import DDLParser
parse_results = DDLParser(ddl).run(output_mode="hql")

**Expected behavior**
Response should not be empty.

**Comment by xnuinside** [comment]
@kukigai fixed in 0.19.6, version is released, added ? to test - https://github.com/xnuinside/simple-ddl-parser/blob/main/tests/test_hql_output_mode.py#L1609. Feel free to open new issue if needed anything more.
