### ISSUE TITLE
When DDL has TBLPROPERTIES, result is empty

### ISSUE THREAD

**Issue by kukigai** [xnuinside/simple-ddl-parser#65]
**Describe the bug**
When DDL has TBLPROPERTIES, result is empty

**To Reproduce**
ddl = """
CREATE EXTERNAL TABLE test (
job_id STRING COMMENT 'test'
)
STORED AS PARQUET LOCATION 'hdfs://test'
TBLPROPERTIES (	
  'parquet.compression'='SNAPPY')
"""
from simple_ddl_parser import DDLParser
parse_results = DDLParser(ddl).run(output_mode="hql")

**Expected behavior**
non empty result

**Comment by xnuinside** [comment]
@kukigai thanks for DDL sample, support for TBLPROPERTIES was not added yet, I will add

**Comment by kukigai** [comment]
another example

ddl = """
CREATE EXTERNAL TABLE `test` (
    `test`   STRING NULL COMMENT 'xxxx',
)
STORED AS INPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  'hdfs://xxxx'
"""
from simple_ddl_parser import DDLParser
parse_results = DDLParser(ddl).run(output_mode="hql")

**Comment by xnuinside** [comment]
same, in 0.19.6, test - https://github.com/xnuinside/simple-ddl-parser/blob/main/tests/test_hql_output_mode.py#L1707
