### ISSUE TITLE
Multi partition is not handled

### ISSUE THREAD

**Issue by kukigai** [xnuinside/simple-ddl-parser#66]
**Describe the bug**
Multi partition is not handled

**To Reproduce**
ddl = """
CREATE EXTERNAL TABLE `test` (
    `test`   STRING NULL COMMENT 'xxxx',
)
PARTITIONED BY (snapshot STRING, cluster STRING)
STORED AS PARQUET LOCATION 'hdfs://xxxx';
"""
from simple_ddl_parser import DDLParser
parse_results = DDLParser(ddl).run(output_mode="hql")

**Expected behavior**
non empty json response

**Comment by xnuinside** [comment]
I will take care on all issues tomorrow, if you have something else - feel free to add samples, to add more in second release :) and thanks for the reports one more time @kukigai

**Comment by kukigai** [comment]
@xnuinside this is all i found.  Thanks for your quick turnaround!

**Comment by xnuinside** [comment]
fixed in 0.19.6, released, test added - https://github.com/xnuinside/simple-ddl-parser/blob/main/tests/test_hql_output_mode.py#L1652 @kukigai
