### ISSUE TITLE
semi colon in COMMENT is not handled

### ISSUE THREAD

**Issue by kukigai** [xnuinside/simple-ddl-parser#68]
**Describe the bug**
semi colon is not handled

**To Reproduce**
ddl = """
CREATE EXTERNAL TABLE `test` (
    `test`   STRING NULL COMMENT 'test;',
)
COMMENT 'test'
"""
from simple_ddl_parser import DDLParser
parse_results = DDLParser(ddl).run(output_mode="hql")

**Expected behavior**
Non-empty result

**Comment by xnuinside** [comment]
Oh! Symbols!!! :))

**Comment by xnuinside** [comment]
fixed in 0.19.7, test here - https://github.com/xnuinside/simple-ddl-parser/blob/main/tests/test_hql_output_mode.py#L1639
