### ISSUE TITLE
'STORED AS INPUTFORMAT', 'OUTPUTFORMAT', and 'ROW FORMAT SERDE' is not supported

### ISSUE THREAD

**Issue by kukigai** [xnuinside/simple-ddl-parser#69]
**Describe the bug**
'STORED AS INPUTFORMAT' and 'OUTPUTFORMAT' is not supported

**To Reproduce**
ddl = """
CREATE EXTERNAL TABLE test (
test STRING NULL COMMENT 'xxxx',
)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
STORED AS INPUTFORMAT
'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'
OUTPUTFORMAT
'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
'hdfs://xxxx'
"""

**Expected behavior**
non empty response

**Comment by xnuinside** [comment]
ROW FORMAT SERDE - supported, if you will try `CREATE EXTERNAL TABLE test (
test STRING NULL COMMENT 'xxxx',
)
ROW FORMAT SERDE
'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'` you will got the result,  but OUTPUTFORMAT & STORED AS INPUTFORMAT - not, I will add them

**Comment by xnuinside** [comment]
@kukigai, support added in 0.19.7 (already released), test here - https://github.com/xnuinside/simple-ddl-parser/blob/main/tests/test_hql_output_mode.py#L1769
