### ISSUE TITLE
Less output with 'on update' string

### ISSUE THREAD

**Issue by harusamee** [xnuinside/simple-ddl-parser#80]
**Describe the bug**
The `sdp` command generates less output than normal when a input file contains the string 'on update'

**To Reproduce**

1. install from pip
```bash
$ pip3 install simple-ddl-parser
Defaulting to user installation because normal site-packages is not writeable
Collecting simple-ddl-parser
  Downloading simple_ddl_parser-0.19.9-py3-none-any.whl (29 kB)
Collecting ply<4.0,>=3.11
  Downloading ply-3.11-py2.py3-none-any.whl (49 kB)
     |████████████████████████████████| 49 kB 9.2 MB/s
Installing collected packages: ply, simple-ddl-parser
Successfully installed ply-3.11 simple-ddl-parser-0.19.9
```
2. Run `sdp` command
```bash
$ cat <<'EOF' > test.sql
create table test(
  `id` bigint not null,
  `updated_at` timestamp(3) not null default current_timestamp(3) on update current_timestamp(3),
  primary key (id)
);
EOF
$ ~/.local/bin/sdp test.sql  -v
Start parsing file schema/test.sql

File with result was saved to >> schemas folder
[{'primary_key': ['id']}]
```

**Expected behavior**
Output json like following with some `on update` key...

```
[{'alter': {},
  'checks': [],
  'columns': [{'check': None,
               'default': None,
               'name': '`id`',
               'nullable': False,
               'references': None,
               'size': None,
               'type': 'bigint',
               'unique': False},
              {'check': None,
               'default': 'current_timestamp(3)',
               'name': '`updated_at`',
               'nullable': False,
               'references': None,
               'size': 3,
               'type': 'timestamp',
               'unique': False}],
  'index': [],
  'partitioned_by': [],
  'primary_key': ['id'],
  'schema': None,
  'table_name': 'test',
  'tablespace': None}]
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS

**Comment by xnuinside** [comment]
@harusamee hi! thanks for the report, I think, the reason in function after on update, because https://github.com/xnuinside/simple-ddl-parser/blob/main/tests/test_references.py#L75 here test without function. I will fix it tomorrow evening and will release patch version with fix.

**Comment by xnuinside** [comment]
okay,  I found the reason : problem that on update supported only with references

**Comment by xnuinside** [comment]
@harusamee version 0.20.0 released with support MySQL on update statement. Test added here: https://github.com/xnuinside/simple-ddl-parser/blob/main/tests/test_mysql.py#L58

If you will need anything else or will see a bug - feel free to open a new issue. Thanks for the report one more time!
