### ISSUE TITLE
omymodels.errors.NoTablesError: No tables was found in DDL input.

### ISSUE THREAD

**Issue by KrunchMuffin** [xnuinside/simple-ddl-parser#81]
**Describe the bug**
No tables was found in DDL input

**To Reproduce**
Generate my DDL from SSMS and import to OMM

**Expected behavior**
find tables to parse

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win10
 - 
[script.sql.txt](https://github.com/xnuinside/simple-ddl-parser/files/7256078/script.sql.txt)

**Comment by xnuinside** [comment]
@KrunchMuffin hi, thanks for the report. Thanks for the sample) it will take a some time to support all things a huge ddl) by the way, I see [] near column names for the first time. What is DB that generate this?

**Comment by KrunchMuffin** [comment]
That is MS sql server. If it encounters words that are reserved or columns
abd tables with hyphens, it will wrap them in square brackets so it doesn't
interfere. If you made a column called desc it would do [desc] since that
is a reserved word .

**Comment by xnuinside** [comment]
@KrunchMuffin got it, thanks :)

**Comment by xnuinside** [comment]
I started to add some statements in v0.20.0 version that I found in your script. Really thanks for the sample. But still a lot of work. I will report when will be the version, that support all of MSSQL things from your script.

**Comment by KrunchMuffin** [comment]
How long before you add it to omymodels?

**Comment by xnuinside** [comment]
@KrunchMuffin I plan to add full support to queries from your sql file in 0.21.0 version, release it and update omymodels after that. I need few days more for that.

**Comment by xnuinside** [comment]
@KrunchMuffin  I released 0.21.0. This this version your full script is parsed well. Tomorrow I will work on Omymodels updates. Will ping you here after release new version in OMyModels

**Comment by xnuinside** [comment]
@KrunchMuffin sorry for taken a long time, I thought release it with 0.11.0 version, but updates that I planned taken much more time.So just released version 0.10.1 https://pypi.org/project/omymodels/  with updated dependency to new simple-ddl-parser 0.21.1. But need also made in OMyModels changes - to remove [] from names before generate code.. it will takes more time. I created issue for this: https://github.com/xnuinside/omymodels/issues/28. I will close this issue and let's continue in omymodels.
