### ISSUE TITLE
keep "<" and ">" special char in columns names when properly quoted

### ISSUE THREAD

**Issue by gtanzi** [xnuinside/simple-ddl-parser#89]
First of all, wanna compliment you for this helpful tool! 

I came into a (possibly?) minor bug when trying to parse an hql file containing column names with special characters "<" or ">" properly quoted like:
`something<2%` float
I found out this is due to "parser.pre_process_line" that insert spaces around "<" and ">" if "(" not in line.
Possible solution is not to insert spaces if "<" ">" are inbetween quotes.

**Comment by xnuinside** [comment]
@gtanzi , hi! Thanks for warm words and reporting the issue. I will be back from vacation on 8 of November and will take a look in the big :) thank you!

**Comment by xnuinside** [comment]
@gtanzi about spaces - I added them because of some issues with parsing HQL structures like this - ARRAY<structcolx:string,coly:string>. I will work on more normal workaround and will try to remove it.

**Comment by xnuinside** [comment]
@gtanzi sorry that it took so much time - worked on another issues, I fixed this problem in 0.22.5. https://github.com/xnuinside/simple-ddl-parser/blob/main/tests/test_hql_output_mode.py#L1888 - test added. Feel free to open the new issue if needed something. Thank you!
